'use strict';

window.AppErrors = {
    // Storage errors
    STORAGE: {
        INVALID_DATE: 'STORAGE_INVALID_DATE',
        ENTRY_NOT_FOUND: 'STORAGE_ENTRY_NOT_FOUND',
        QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
        PARSE_ERROR: 'STORAGE_PARSE_ERROR',
        INVALID_INPUT: 'STORAGE_INVALID_INPUT',
        NOT_FOUND: 'STORAGE_NOT_FOUND',
        INVALID_FORMAT: 'STORAGE_INVALID_FORMAT',
        VERSION_MISMATCH: 'STORAGE_VERSION_MISMATCH'
    },

    // Sync errors
    SYNC: {
        NOT_AUTHENTICATED: 'SYNC_NOT_AUTHENTICATED',
        NETWORK_ERROR: 'SYNC_NETWORK_ERROR',
        CONFLICT: 'SYNC_CONFLICT',
        SUPABASE_NOT_AVAILABLE: 'SYNC_SUPABASE_NOT_AVAILABLE'
    },

    // Auth errors
    AUTH: {
        INVALID_EMAIL: 'AUTH_INVALID_EMAIL',
        SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
        NOT_INITIALIZED: 'AUTH_NOT_INITIALIZED'
    }
};
